DigTech\REST\RESTResource Class Reference
This abstract class serves as the base class for all REST APIs. This class cannot be instantiated directly.
Public Member Functions
__construct ($request, $schema='orders')
Construct the object, allow for CORS, assemble and pre-process the data.
dispatch ()
Process the request and return the response.
Protected Member Functions
addVariable ($varname, $vartype)
Add an input variable with type information (s - string, n - integer, f - float, d = date, t = time, dt = datetime, b = boolean)
response ($data, $status=200)
Format the HTTP status header and json-encode response.
requestStatus ($code)
Get the HTTP status string for a status code.
getRequestVariable ($varName, $default, &$isSet=null)
Get request form data.
Protected Attributes
$_method = ''
HTTP request method.
$_resource = ''
the requested resource name
$_args = array()
URI components following resource name.
$_file = null
input file information for HTTP PUT
$_request = array()
sanitized input data ($_GET and $_PUT values)
$_types = array()
data types for input parameters
$_conn = null
database connection handle for sql string sanitization
$_schema = ''
default database schema
Private Member Functions
sanitizeData ($data, $type=null)
Sanitize input data.
Detailed Description
This abstract class serves as the base class for all REST APIs. This class cannot be instantiated directly.
Definition at line 14 of file Resource.php.
Constructor & Destructor Documentation
__construct()
DigTech\REST\RESTResource::__construct ($request, $schema = 'orders')
Construct the object, allow for CORS, assemble and pre-process the data.
Parameters
$request The request that was received
$schema The default schema to be used for this API
Definition at line 30 of file Resource.php.
References DigTech\REST\RESTResource\addVariable(), DigTech\Logging\Logger\log(), DigTech\REST\RESTResource\response(), and DigTech\REST\RESTResource\sanitizeData().
Member Function Documentation
addVariable()
DigTech\REST\RESTResource::addVariable ($varname, $vartype) [protected]
Add an input variable with type information (s - string, n - integer, f - float, d = date, t = time, dt = datetime, b = boolean)
Parameters
$varname Variable name
$vartype Variable type
Definition at line 134 of file Resource.php.
Referenced by DigTech\REST\RESTResource\__construct().
dispatch()
DigTech\REST\RESTResource::dispatch ()
Process the request and return the response.
Returns
Output of service method
Definition at line 143 of file Resource.php.
References DigTech\REST\RESTResource\$_args, and DigTech\REST\RESTResource\response().
getRequestVariable()
DigTech\REST\RESTResource::getRequestVariable ($varName, $default, & $isSet = null) [protected]
Get request form data.
Parameters
$varName Name of request variable to get
$default Default value if request variable is empty
$isSet Indicates if variable was set
Definition at line 274 of file Resource.php.
requestStatus()
DigTech\REST\RESTResource::requestStatus ($code) [protected]
Get the HTTP status string for a status code.
Parameters
$code The HTTP status code
Returns
Text associated with HTTP status code
Definition at line 255 of file Resource.php.
Referenced by DigTech\REST\RESTResource\response().
response()
DigTech\REST\RESTResource::response ($data, $status = 200) [protected]
Format the HTTP status header and json-encode response.
Parameters
$data Response data to encode and return
$status The HTTP status code for the response
Returns
json-encoded response data
Definition at line 168 of file Resource.php.
References DigTech\Logging\Logger\log(), and DigTech\REST\RESTResource\requestStatus().
Referenced by DigTech\REST\RESTResource\__construct(), and DigTech\REST\RESTResource\dispatch().
sanitizeData()
DigTech\REST\RESTResource::sanitizeData ($data, $type = null) [private]
Sanitize input data.
Parameters
$data Input data to be sanitized
$type Data type for input data if not array
Returns
Sanitized input data
Definition at line 197 of file Resource.php.
References DigTech\REST\RESTResource\sanitizeData().
Referenced by DigTech\REST\RESTResource\__construct(), and DigTech\REST\RESTResource\sanitizeData().
Member Data Documentation
$_args
DigTech\REST\RESTResource::$_args = array() [protected]
URI components following resource name.
Definition at line 18 of file Resource.php.
Referenced by DigTech\REST\RESTResource\dispatch().
$_conn
DigTech\REST\RESTResource::$_conn = null [protected]
database connection handle for sql string sanitization
Definition at line 22 of file Resource.php.
$_file
DigTech\REST\RESTResource::$_file = null [protected]
input file information for HTTP PUT
Definition at line 19 of file Resource.php.
$_method
DigTech\REST\RESTResource::$_method = '' [protected]
HTTP request method.
Definition at line 16 of file Resource.php.
$_request
DigTech\REST\RESTResource::$_request = array() [protected]
sanitized input data ($_GET and $_PUT values)
Definition at line 20 of file Resource.php.
$_resource
DigTech\REST\RESTResource::$_resource = '' [protected]
the requested resource name
Definition at line 17 of file Resource.php.
$_schema
DigTech\REST\RESTResource::$_schema = '' [protected]
default database schema
Definition at line 23 of file Resource.php.
$_types
DigTech\REST\RESTResource::$_types = array() [protected]
data types for input parameters
Definition at line 21 of file Resource.php.
The documentation for this class was generated from the following file:
DigTech/REST/Resource.php