DigTech\REST\SecureResource Class Reference
This class adds authentication/access control functionality.
Public Member Functions
__construct ($request, $schema='digtech')
Construct the object, allow for CORS, assemble and pre-process the data.
dispatch ()
Dispatch the request if it is authorized. Otherwise return HTTP 401.
Protected Member Functions
isAuthorized ()
Check request credentials.
addVariable ($varname, $vartype)
Add an input variable with type information (s - string, n - integer, f - float, d = date, t = time, dt = datetime, b = boolean)
response ($data, $status=200)
Format the HTTP status header and json-encode response.
requestStatus ($code)
Get the HTTP status string for a status code.
getRequestVariable ($varName, $default, &$isSet=null)
Get request form data.
setQueryVariables ($queryVars)
Set query variables from URL query.
getQueryVariable ($varName)
Retrieve query variable.
Protected Attributes
$_authorizationHeader
$_authUser = null
AuthUser object.
$_method = ''
HTTP request method.
$_resource = ''
the requested resource name
$_args = []
URI components following resource name.
$_query = []
query parameters from URI
$_file = null
input file information for HTTP PUT
$_request = []
sanitized input data ($_GET and $_PUT values)
$_types = []
data types for input parameters
$_conn = null
database connection handle for sql string sanitization
$_schema = ''
default database schema
Private Member Functions
sanitizeData ($data, $type=null)
Sanitize input data.
Detailed Description
This class adds authentication/access control functionality.
Definition at line 12 of file SecureResource.php.
Constructor & Destructor Documentation
__construct()
DigTech\REST\SecureResource::__construct ($request, $schema = 'digtech')
Construct the object, allow for CORS, assemble and pre-process the data.
Parameters
$request The request that was received
$schema The default schema to be used for this API
Reimplemented from DigTech\REST\Resource.
Definition at line 22 of file SecureResource.php.
References DigTech\REST\SecureResource\isAuthorized().
Member Function Documentation
addVariable()
DigTech\REST\Resource::addVariable ($varname, $vartype) [protected], [inherited]
Add an input variable with type information (s - string, n - integer, f - float, d = date, t = time, dt = datetime, b = boolean)
Parameters
$varname Variable name
$vartype Variable type
Definition at line 135 of file Resource.php.
Referenced by DigTech\REST\Resource\__construct().
dispatch()
DigTech\REST\SecureResource::dispatch ()
Dispatch the request if it is authorized. Otherwise return HTTP 401.
Reimplemented from DigTech\REST\Resource.
Definition at line 59 of file SecureResource.php.
References DigTech\REST\SecureResource\isAuthorized(), DigTech\Logging\Logger\log(), and DigTech\REST\Resource\response().
getQueryVariable()
DigTech\REST\Resource::getQueryVariable ($varName) [protected], [inherited]
Retrieve query variable.
Parameters
$varName Name of variable to retrieve
Returns
Value of variable (mixed) or null
Definition at line 310 of file Resource.php.
getRequestVariable()
DigTech\REST\Resource::getRequestVariable ($varName, $default, & $isSet = null) [protected], [inherited]
Get request form data.
Parameters
$varName Name of request variable to get
$default Default value if request variable is empty
$isSet Indicates if variable was set
Definition at line 275 of file Resource.php.
isAuthorized()
DigTech\REST\SecureResource::isAuthorized () [protected]
Check request credentials.
Returns
true/false to indicate if request is authorized
Todo
Todo This is where the authentication logic should be placed. The auth handler can interpret the Authorization header as desired.
<
Todo
Todo This needs to be fixed
Definition at line 41 of file SecureResource.php.
Referenced by DigTech\REST\SecureResource\__construct(), and DigTech\REST\SecureResource\dispatch().
requestStatus()
DigTech\REST\Resource::requestStatus ($code) [protected], [inherited]
Get the HTTP status string for a status code.
Parameters
$code The HTTP status code
Returns
Text associated with HTTP status code
Definition at line 256 of file Resource.php.
Referenced by DigTech\REST\Resource\response().
response()
DigTech\REST\Resource::response ($data, $status = 200) [protected], [inherited]
Format the HTTP status header and json-encode response.
Parameters
$data Response data to encode and return
$status The HTTP status code for the response
Returns
json-encoded response data
Definition at line 169 of file Resource.php.
References DigTech\Logging\Logger\log(), and DigTech\REST\Resource\requestStatus().
Referenced by DigTech\REST\Resource\__construct(), DigTech\REST\Resource\dispatch(), and DigTech\REST\SecureResource\dispatch().
sanitizeData()
DigTech\REST\Resource::sanitizeData ($data, $type = null) [private], [inherited]
Sanitize input data.
Parameters
$data Input data to be sanitized
$type Data type for input data if not array
Returns
Sanitized input data
Definition at line 198 of file Resource.php.
References DigTech\REST\Resource\sanitizeData().
Referenced by DigTech\REST\Resource\__construct(), and DigTech\REST\Resource\sanitizeData().
setQueryVariables()
DigTech\REST\Resource::setQueryVariables ($queryVars) [protected], [inherited]
Set query variables from URL query.
Parameters
$queryVars The list of variables to received on request
Definition at line 300 of file Resource.php.
Member Data Documentation
$_args
DigTech\REST\Resource::$_args = [] [protected], [inherited]
URI components following resource name.
Definition at line 18 of file Resource.php.
Referenced by DigTech\REST\Resource\dispatch().
$_authorizationHeader
DigTech\REST\SecureResource::$_authorizationHeader [protected]
Definition at line 14 of file SecureResource.php.
$_authUser
DigTech\REST\SecureResource::$_authUser = null [protected]
AuthUser object.
Definition at line 15 of file SecureResource.php.
$_conn
DigTech\REST\Resource::$_conn = null [protected], [inherited]
database connection handle for sql string sanitization
Definition at line 23 of file Resource.php.
$_file
DigTech\REST\Resource::$_file = null [protected], [inherited]
input file information for HTTP PUT
Definition at line 20 of file Resource.php.
$_method
DigTech\REST\Resource::$_method = '' [protected], [inherited]
HTTP request method.
Definition at line 16 of file Resource.php.
$_query
DigTech\REST\Resource::$_query = [] [protected], [inherited]
query parameters from URI
Definition at line 19 of file Resource.php.
$_request
DigTech\REST\Resource::$_request = [] [protected], [inherited]
sanitized input data ($_GET and $_PUT values)
Definition at line 21 of file Resource.php.
$_resource
DigTech\REST\Resource::$_resource = '' [protected], [inherited]
the requested resource name
Definition at line 17 of file Resource.php.
$_schema
DigTech\REST\Resource::$_schema = '' [protected], [inherited]
default database schema
Definition at line 24 of file Resource.php.
$_types
DigTech\REST\Resource::$_types = [] [protected], [inherited]
data types for input parameters
Definition at line 22 of file Resource.php.
The documentation for this class was generated from the following file:
DigTech/REST/SecureResource.php