DigTech\Database\MySQL\Record Class Reference
Public Member Functions
__construct ()
get ($columnName)
Get the value of a column.
set ($columnName, $value)
Set the value of a column.
setKey ($columnName, $value)
Set the value of a key field.
isKeyColumn ($columnName)
Check of column is in primary key.
buildKeyString ($keys=null)
Build string for SQL WHERE to retrieve by primary key or keys parameter.
getDirty ($columnName)
Check of column is dirty.
setDirty ($columnName)
Set column is dirty.
clearDirty ($columnName)
Clear column dirty flag.
isDirty ()
Check if record is dirty.
resetDirty ()
Reset dirty flags for the record.
setReadOnly ($columnName)
Set the read-only flag for a column.
clearReadOnly ($columnName)
Clear the read-only flag for a column.
isReadOnly ($columnName)
Get the read-only flag for a column.
setNoQuote ($columnName)
Set the no quote flag for a column.
clearNoQuote ($columnName)
Clear the no quote flag for a column.
isNoQuote ($columnName)
Get the no quote flag for a column.
isSystemColumn ($col)
Is this a system/administrative column?
copyRecord ()
Copy this object to another onea.
read ()
Read the record from the database.
insert ()
Insert a new record into the database.
update ()
Update a record in the database.
delete ()
Delete a record from the database.
Protected Member Functions
reset ()
Reset the column list and dirty flags.
Protected Attributes
$_conn
Database connection object.
$_tableName
Name of target table.
$_primaryKeys
Array of primary key columns.
$_columnList
Array of columns and values.
$_dirtyFlags
Array of dirty column flags.
$_readOnlyFlags
Array of read-only column flags.
$_noQuoteFlags
Array of no-quote flags.
Detailed Description
Definition at line 7 of file Record.php.
Constructor & Destructor Documentation
__construct()
DigTech\Database\MySQL\Record::__construct ()
Definition at line 9 of file Record.php.
Member Function Documentation
buildKeyString()
DigTech\Database\Record::buildKeyString ($keys = null) [inherited]
Build string for SQL WHERE to retrieve by primary key or keys parameter.
Parameters
$keys Array of column/value pairs to use for query ($keys[columnName] = value)
Definition at line 111 of file Record.php.
References DigTech\Database\Record\$_primaryKeys.
Referenced by DigTech\Database\Record\delete(), DigTech\Database\Record\read(), and DigTech\Database\Record\update().
clearDirty()
DigTech\Database\Record::clearDirty ($columnName) [inherited]
Clear column dirty flag.
Parameters
$columnName The name of the column to clear the dirty flag for
Definition at line 156 of file Record.php.
Referenced by DigTech\Database\Record\resetDirty().
clearNoQuote()
DigTech\Database\Record::clearNoQuote ($columnName) [inherited]
Clear the no quote flag for a column.
Parameters
$columnName The name of the column name to clear as no quote
Definition at line 236 of file Record.php.
clearReadOnly()
DigTech\Database\Record::clearReadOnly ($columnName) [inherited]
Clear the read-only flag for a column.
Parameters
$columnName The name of the column name to clear as not read-only
Definition at line 207 of file Record.php.
copyRecord()
DigTech\Database\Record::copyRecord () [inherited]
Copy this object to another onea.
Returns
New DBRecord object that is a copy of this object
Definition at line 280 of file Record.php.
delete()
DigTech\Database\Record::delete () [inherited]
Delete a record from the database.
Definition at line 534 of file Record.php.
References DigTech\Database\Record\buildKeyString(), and DigTech\Logging\Logger\log().
get()
DigTech\Database\Record::get ($columnName) [inherited]
Get the value of a column.
Parameters
$columnName The name of the column to retrieve
Returns
Value of column or null
Definition at line 49 of file Record.php.
getDirty()
DigTech\Database\Record::getDirty ($columnName) [inherited]
Check of column is dirty.
Parameters
$columnName The name of the column to check
Return values
true The column is dirty
false The column is not dirty
Returns
Boolean true/false if column is dirty
Definition at line 138 of file Record.php.
Referenced by DigTech\Database\Record\insert(), and DigTech\Database\Record\update().
insert()
DigTech\Database\Record::insert () [inherited]
Insert a new record into the database.
Definition at line 360 of file Record.php.
References DigTech\Database\Record\getDirty(), DigTech\Database\Record\isKeyColumn(), DigTech\Database\Record\isNoQuote(), DigTech\Database\Record\isReadOnly(), DigTech\Database\Record\isSystemColumn(), DigTech\Logging\Logger\log(), DigTech\Database\Record\read(), and DigTech\Database\Record\reset().
isDirty()
DigTech\Database\Record::isDirty () [inherited]
Check if record is dirty.
Return values
true A column in the record has been modified
false No columns in the record have been modified
Returns
Boolean true/false if record has been modified
Definition at line 167 of file Record.php.
isKeyColumn()
DigTech\Database\Record::isKeyColumn ($columnName) [inherited]
Check of column is in primary key.
Parameters
$columnName The name of the column to check
Return values
true The column is in the primary key
false The column is not in the primary key
Returns
Boolean true/false if column is in primary key
Definition at line 95 of file Record.php.
Referenced by DigTech\Database\Record\insert(), DigTech\Database\Record\read(), DigTech\Database\Record\set(), and DigTech\Database\Record\update().
isNoQuote()
DigTech\Database\Record::isNoQuote ($columnName) [inherited]
Get the no quote flag for a column.
Return values
true The column is no quote
false The column is not no quote
Returns
The no quote state for the column
Definition at line 247 of file Record.php.
Referenced by DigTech\Database\Record\insert(), and DigTech\Database\Record\update().
isReadOnly()
DigTech\Database\Record::isReadOnly ($columnName) [inherited]
Get the read-only flag for a column.
Return values
true The column is read-only
false The column is not read-only
Returns
The read-only state for the column
Definition at line 218 of file Record.php.
Referenced by DigTech\Database\Record\insert(), and DigTech\Database\Record\update().
isSystemColumn()
DigTech\Database\Record::isSystemColumn ($col) [inherited]
Is this a system/administrative column?
Parameters
$col Column name to check
Returns
Whether column is a system/administrative column
Return values
true Column is a system/adminstrative column
false Column is not a system/adminstrative column
Definition at line 259 of file Record.php.
Referenced by DigTech\Database\Record\insert(), and DigTech\Database\Record\update().
read()
DigTech\Database\Record::read () [inherited]
Read the record from the database.
Definition at line 295 of file Record.php.
References DigTech\Database\Record\buildKeyString(), DigTech\Database\Record\isKeyColumn(), DigTech\Logging\Logger\log(), DigTech\Database\Record\resetDirty(), and DigTech\Database\Record\setKey().
Referenced by DigTech\Database\Record\insert().
reset()
DigTech\Database\Record::reset () [protected], [inherited]
Reset the column list and dirty flags.
Definition at line 38 of file Record.php.
Referenced by DigTech\Database\Record\__construct(), and DigTech\Database\Record\insert().
resetDirty()
DigTech\Database\Record::resetDirty () [inherited]
Reset dirty flags for the record.
Definition at line 186 of file Record.php.
References DigTech\Database\Record\clearDirty().
Referenced by DigTech\Database\Record\read(), and DigTech\Database\Record\update().
set()
DigTech\Database\Record::set ($columnName, $value) [inherited]
Set the value of a column.
Parameters
$columnName The name of the column to set
$value The value to store in the column
Definition at line 63 of file Record.php.
References DigTech\Database\Record\isKeyColumn(), and DigTech\Database\Record\setKey().
setDirty()
DigTech\Database\Record::setDirty ($columnName) [inherited]
Set column is dirty.
Parameters
$columnName The name of the column to mark as dirty
Definition at line 147 of file Record.php.
setKey()
DigTech\Database\Record::setKey ($columnName, $value) [inherited]
Set the value of a key field.
Parameters
$columnName The name of the key to set
$value The value to store in the key
Definition at line 83 of file Record.php.
Referenced by DigTech\Database\Record\read(), and DigTech\Database\Record\set().
setNoQuote()
DigTech\Database\Record::setNoQuote ($columnName) [inherited]
Set the no quote flag for a column.
Parameters
$columnName The name of the column name to set as no quote
Definition at line 227 of file Record.php.
setReadOnly()
DigTech\Database\Record::setReadOnly ($columnName) [inherited]
Set the read-only flag for a column.
Parameters
$columnName The name of the column name to set as read-only
Definition at line 198 of file Record.php.
update()
DigTech\Database\Record::update () [inherited]
Update a record in the database.
Definition at line 455 of file Record.php.
References DigTech\Database\Record\buildKeyString(), DigTech\Database\Record\getDirty(), DigTech\Database\Record\isKeyColumn(), DigTech\Database\Record\isNoQuote(), DigTech\Database\Record\isReadOnly(), DigTech\Database\Record\isSystemColumn(), DigTech\Logging\Logger\log(), and DigTech\Database\Record\resetDirty().
Member Data Documentation
$_columnList
DigTech\Database\Record::$_columnList [protected], [inherited]
Array of columns and values.
Definition at line 16 of file Record.php.
$_conn
DigTech\Database\Record::$_conn [protected], [inherited]
Database connection object.
Definition at line 13 of file Record.php.
$_dirtyFlags
DigTech\Database\Record::$_dirtyFlags [protected], [inherited]
Array of dirty column flags.
Definition at line 17 of file Record.php.
$_noQuoteFlags
DigTech\Database\Record::$_noQuoteFlags [protected], [inherited]
Array of no-quote flags.
Definition at line 19 of file Record.php.
$_primaryKeys
DigTech\Database\Record::$_primaryKeys [protected], [inherited]
Array of primary key columns.
Definition at line 15 of file Record.php.
Referenced by DigTech\Database\Record\buildKeyString().
$_readOnlyFlags
DigTech\Database\Record::$_readOnlyFlags [protected], [inherited]
Array of read-only column flags.
Definition at line 18 of file Record.php.
$_tableName
DigTech\Database\Record::$_tableName [protected], [inherited]
Name of target table.
Definition at line 14 of file Record.php.
The documentation for this class was generated from the following file:
DigTech/Database/MySQL/Record.php