DigTech\Logging\Logger Class Reference
This class provides logging support for errors, warnings, and debug information.
Public Member Functions
__construct ()
Object constructor.
Static Public Member Functions
static configure ($config)
static setEnabled ($enabled=true)
Enable/disable all logging.
static setDebugEnabled ($enabled=true)
Enable/disable debug logging.
static setWarningEnabled ($enabled=true)
Enable/disable warning logging.
static setErrorEnabled ($enabled=true)
Enable/disable error logging.
static log ($format)
Output a message to the log.
static debug ($format)
Output a debug message to the log with additiona diagnostic information.
static warning ($format)
Output a warning message to the log.
static error ($format)
Output an error message to the log with source/line information.
static setLogFile ($fileName=null)
Static Protected Member Functions
static output ($message)
Common output handler for all log messages.
Static Protected Attributes
static $_enabled = true
Flag to indicate if all logging is enabled.
static $_debugEnabled = true
Flag to indicate if debug logging is enabled.
static $_warningEnabled = true
Flag to indicate if warning logging is enabled.
static $_errorEnabled = true
Flag to indicate if error logging is enabled.
static $_fileName = null
File name if logging is sent to file.
Detailed Description
This class provides logging support for errors, warnings, and debug information.
Definition at line 10 of file Logger.php.
Constructor & Destructor Documentation
__construct()
DigTech\Logging\Logger::__construct ()
Object constructor.
Definition at line 21 of file Logger.php.
Member Function Documentation
configure()
static DigTech\Logging\Logger::configure ($config) [static]
Definition at line 25 of file Logger.php.
References DigTech\Logging\Logger\setDebugEnabled(), DigTech\Logging\Logger\setEnabled(), DigTech\Logging\Logger\setErrorEnabled(), DigTech\Logging\Logger\setLogFile(), and DigTech\Logging\Logger\setWarningEnabled().
debug()
static DigTech\Logging\Logger::debug ($format) [static]
Output a debug message to the log with additiona diagnostic information.
Parameters
$format A printf-stype format string followed by parameters
Definition at line 95 of file Logger.php.
References DigTech\Logging\Logger\output().
error()
static DigTech\Logging\Logger::error ($format) [static]
Output an error message to the log with source/line information.
Parameters
$format A printf-stype format string followed by parameters
Definition at line 149 of file Logger.php.
References DigTech\Logging\Logger\output().
Referenced by DigTech\Database\MySQL\Connection\connect().
log()
static DigTech\Logging\Logger::log ($format) [static]
Output a message to the log.
Parameters
$format A printf-stype format string followed by parameters
Definition at line 74 of file Logger.php.
References DigTech\Logging\Logger\output().
Referenced by DigTech\REST\Resource\__construct(), DigTech\REST\APIInterface\autoloadResource(), DigTech\Database\MySQL\Connection\connect(), DigTech\Database\Record\delete(), DigTech\Database\MySQL\Connection\disconnect(), DigTech\REST\SecureResource\dispatch(), DigTech\Database\Record\insert(), DigTech\REST\APIInterface\phpErrorHandler(), DigTech\Database\MySQL\Connection\query(), DigTech\Database\Record\read(), DigTech\REST\Resource\response(), DigTech\REST\APIInterface\serviceRequest(), and DigTech\Database\Record\update().
output()
static DigTech\Logging\Logger::output ($message) [static], [protected]
Common output handler for all log messages.
Parameters
$message The message to be output
Definition at line 175 of file Logger.php.
Referenced by DigTech\Logging\Logger\debug(), DigTech\Logging\Logger\error(), DigTech\Logging\Logger\log(), and DigTech\Logging\Logger\warning().
setDebugEnabled()
static DigTech\Logging\Logger::setDebugEnabled ($enabled = true) [static]
Enable/disable debug logging.
Parameters
$enabled Set to true to enable logging, false to disable logging
Definition at line 47 of file Logger.php.
Referenced by DigTech\Logging\Logger\configure().
setEnabled()
static DigTech\Logging\Logger::setEnabled ($enabled = true) [static]
Enable/disable all logging.
Parameters
$enabled Set to true to enable logging, false to disable logging
Definition at line 38 of file Logger.php.
Referenced by DigTech\Logging\Logger\configure().
setErrorEnabled()
static DigTech\Logging\Logger::setErrorEnabled ($enabled = true) [static]
Enable/disable error logging.
Parameters
$enabled Set to true to enable logging, false to disable logging
Definition at line 65 of file Logger.php.
Referenced by DigTech\Logging\Logger\configure().
setLogFile()
static DigTech\Logging\Logger::setLogFile ($fileName = null) [static]
Definition at line 200 of file Logger.php.
Referenced by DigTech\Logging\Logger\configure().
setWarningEnabled()
static DigTech\Logging\Logger::setWarningEnabled ($enabled = true) [static]
Enable/disable warning logging.
Parameters
$enabled Set to true to enable logging, false to disable logging
Definition at line 56 of file Logger.php.
Referenced by DigTech\Logging\Logger\configure().
warning()
static DigTech\Logging\Logger::warning ($format) [static]
Output a warning message to the log.
Parameters
$format A printf-stype format string followed by parameters
Definition at line 128 of file Logger.php.
References DigTech\Logging\Logger\output().
Member Data Documentation
$_debugEnabled
DigTech\Logging\Logger::$_debugEnabled = true [static], [protected]
Flag to indicate if debug logging is enabled.
Definition at line 13 of file Logger.php.
$_enabled
DigTech\Logging\Logger::$_enabled = true [static], [protected]
Flag to indicate if all logging is enabled.
Definition at line 12 of file Logger.php.
$_errorEnabled
DigTech\Logging\Logger::$_errorEnabled = true [static], [protected]
Flag to indicate if error logging is enabled.
Definition at line 15 of file Logger.php.
$_fileName
DigTech\Logging\Logger::$_fileName = null [static], [protected]
File name if logging is sent to file.
Definition at line 16 of file Logger.php.
$_warningEnabled
DigTech\Logging\Logger::$_warningEnabled = true [static], [protected]
Flag to indicate if warning logging is enabled.
Definition at line 14 of file Logger.php.
The documentation for this class was generated from the following file:
DigTech/Logging/Logger.php