DigTech\REST\Resource Class Reference
This abstract class serves as the base class for all REST APIs. This class cannot be instantiated directly.
Public Member Functions
__construct ($request, $schema='digtech')
Construct the object, allow for CORS, assemble and pre-process the data.
dispatch ()
Process the request and return the response.
Protected Member Functions
addVariable ($varname, $vartype)
Add an input variable with type information (s - string, n - integer, f - float, d = date, t = time, dt = datetime, b = boolean)
response ($data, $status=200)
Format the HTTP status header and json-encode response.
requestStatus ($code)
Get the HTTP status string for a status code.
getRequestVariable ($varName, $default, &$isSet=null)
Get request form data.
setQueryVariables ($queryVars)
Set query variables from URL query.
getQueryVariable ($varName)
Retrieve query variable.
Protected Attributes
$_method = ''
HTTP request method.
$_resource = ''
the requested resource name
$_args = []
URI components following resource name.
$_query = []
query parameters from URI
$_file = null
input file information for HTTP PUT
$_request = []
sanitized input data ($_GET and $_PUT values)
$_types = []
data types for input parameters
$_conn = null
database connection handle for sql string sanitization
$_schema = ''
default database schema
Private Member Functions
sanitizeData ($data, $type=null)
Sanitize input data.
Detailed Description
This abstract class serves as the base class for all REST APIs. This class cannot be instantiated directly.
Definition at line 14 of file Resource.php.
Constructor & Destructor Documentation
__construct()
DigTech\REST\Resource::__construct ($request, $schema = 'digtech')
Construct the object, allow for CORS, assemble and pre-process the data.
Parameters
$request The request that was received
$schema The default schema to be used for this API
Reimplemented in DigTech\REST\SecureResource.
Definition at line 31 of file Resource.php.
References $globalConfiguration, DigTech\REST\Resource\addVariable(), getGlobalConfiguration(), DigTech\Logging\Logger\log(), DigTech\REST\Resource\response(), and DigTech\REST\Resource\sanitizeData().
Member Function Documentation
addVariable()
DigTech\REST\Resource::addVariable ($varname, $vartype) [protected]
Add an input variable with type information (s - string, n - integer, f - float, d = date, t = time, dt = datetime, b = boolean)
Parameters
$varname Variable name
$vartype Variable type
Definition at line 135 of file Resource.php.
Referenced by DigTech\REST\Resource\__construct().
dispatch()
DigTech\REST\Resource::dispatch ()
Process the request and return the response.
Returns
Output of service method
Reimplemented in DigTech\REST\SecureResource.
Definition at line 144 of file Resource.php.
References DigTech\REST\Resource\$_args, and DigTech\REST\Resource\response().
getQueryVariable()
DigTech\REST\Resource::getQueryVariable ($varName) [protected]
Retrieve query variable.
Parameters
$varName Name of variable to retrieve
Returns
Value of variable (mixed) or null
Definition at line 310 of file Resource.php.
getRequestVariable()
DigTech\REST\Resource::getRequestVariable ($varName, $default, & $isSet = null) [protected]
Get request form data.
Parameters
$varName Name of request variable to get
$default Default value if request variable is empty
$isSet Indicates if variable was set
Definition at line 275 of file Resource.php.
requestStatus()
DigTech\REST\Resource::requestStatus ($code) [protected]
Get the HTTP status string for a status code.
Parameters
$code The HTTP status code
Returns
Text associated with HTTP status code
Definition at line 256 of file Resource.php.
Referenced by DigTech\REST\Resource\response().
response()
DigTech\REST\Resource::response ($data, $status = 200) [protected]
Format the HTTP status header and json-encode response.
Parameters
$data Response data to encode and return
$status The HTTP status code for the response
Returns
json-encoded response data
Definition at line 169 of file Resource.php.
References DigTech\Logging\Logger\log(), and DigTech\REST\Resource\requestStatus().
Referenced by DigTech\REST\Resource\__construct(), DigTech\REST\Resource\dispatch(), and DigTech\REST\SecureResource\dispatch().
sanitizeData()
DigTech\REST\Resource::sanitizeData ($data, $type = null) [private]
Sanitize input data.
Parameters
$data Input data to be sanitized
$type Data type for input data if not array
Returns
Sanitized input data
Definition at line 198 of file Resource.php.
References DigTech\REST\Resource\sanitizeData().
Referenced by DigTech\REST\Resource\__construct(), and DigTech\REST\Resource\sanitizeData().
setQueryVariables()
DigTech\REST\Resource::setQueryVariables ($queryVars) [protected]
Set query variables from URL query.
Parameters
$queryVars The list of variables to received on request
Definition at line 300 of file Resource.php.
Member Data Documentation
$_args
DigTech\REST\Resource::$_args = [] [protected]
URI components following resource name.
Definition at line 18 of file Resource.php.
Referenced by DigTech\REST\Resource\dispatch().
$_conn
DigTech\REST\Resource::$_conn = null [protected]
database connection handle for sql string sanitization
Definition at line 23 of file Resource.php.
$_file
DigTech\REST\Resource::$_file = null [protected]
input file information for HTTP PUT
Definition at line 20 of file Resource.php.
$_method
DigTech\REST\Resource::$_method = '' [protected]
HTTP request method.
Definition at line 16 of file Resource.php.
$_query
DigTech\REST\Resource::$_query = [] [protected]
query parameters from URI
Definition at line 19 of file Resource.php.
$_request
DigTech\REST\Resource::$_request = [] [protected]
sanitized input data ($_GET and $_PUT values)
Definition at line 21 of file Resource.php.
$_resource
DigTech\REST\Resource::$_resource = '' [protected]
the requested resource name
Definition at line 17 of file Resource.php.
$_schema
DigTech\REST\Resource::$_schema = '' [protected]
default database schema
Definition at line 24 of file Resource.php.
$_types
DigTech\REST\Resource::$_types = [] [protected]
data types for input parameters
Definition at line 22 of file Resource.php.
The documentation for this class was generated from the following file:
DigTech/REST/Resource.php