DigTech\REST\APIInterface Class Reference
This class is the primary dispatcher used to dispatch REST requests.
Static Public Member Functions
static serviceRequest ()
Static Protected Member Functions
static autoloadResource ($className)
autoload handler for loading resources
static phpErrorHandler ($errno, $errstr, $file, $line)
Detailed Description
This class is the primary dispatcher used to dispatch REST requests.
Definition at line 15 of file APIInterface.php.
Member Function Documentation
autoloadResource()
static DigTech\REST\APIInterface::autoloadResource ($className) [static], [protected]
autoload handler for loading resources
Parameters
$className The class name to load
Definition at line 21 of file APIInterface.php.
References DigTech\Logging\Logger\log().
phpErrorHandler()
static DigTech\REST\APIInterface::phpErrorHandler ($errno, $errstr, $file, $line) [static], [protected]
Definition at line 36 of file APIInterface.php.
References DigTech\Logging\Logger\log().
serviceRequest()
static DigTech\REST\APIInterface::serviceRequest () [static]
Definition at line 46 of file APIInterface.php.
References DigTech\Logging\Logger\log().
The documentation for this class was generated from the following file:
DigTech/REST/APIInterface.php